on:
  push:
    branches: ["main"]
    paths:
      - Go/**
  workflow_dispatch:

defaults:
  run:
    working-directory: Go

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "~1.20.0"
      - run: go test -v ./...
